language: r
sudo: required
r_github_packages:
  - jimhester/lintr
  - jimhester/covr
after_success:
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'library(covr);coveralls()'
