language: r
sudo: required

r_github_packages:
 - jimhester/lintr
 install:
  - Rscript -e 'devtools::install_deps("Package")'
script:
  - Rscript -e 'devtools::check("Package")'
 after_success:
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package()'
